"use client";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ChevronDown } from "lucide-react";

const faqs = [
  {
    q: "Is BrandForge AI free to use?",
    a: "Yes! Our Starter plan is completely free forever with 20 AI generations per month. No credit card required to get started.",
  },
  {
    q: "What AI model does BrandForge use?",
    a: "BrandForge AI is powered by Google Gemini 1.5 Flash, one of the fastest and most capable AI models available. It's optimized for creative, marketing-focused content generation.",
  },
  {
    q: "Can I use the generated content commercially?",
    a: "Absolutely! All content generated by BrandForge AI is yours to use however you like — including for commercial purposes, client work, and resale.",
  },
  {
    q: "How many platforms does BrandForge support?",
    a: "BrandForge supports 10+ platforms including Instagram, Twitter/X, LinkedIn, Facebook, TikTok, Pinterest, YouTube, Google Ads, Email, and more. Pro and Agency plans unlock all platforms.",
  },
  {
    q: "Can I customize the AI to match my brand voice?",
    a: "Yes! The Brand Kit feature lets you store your tone of voice, brand guidelines, target audience, and recurring hashtags. Every generation will stay perfectly on-brand.",
  },
  {
    q: "What happens when I run out of credits?",
    a: "You'll receive a notification when you're running low. You can upgrade your plan at any time or purchase a credit add-on pack without changing your subscription.",
  },
  {
    q: "Does BrandForge offer a free trial for paid plans?",
    a: "All paid plans come with a 14-day free trial. No credit card required to start. If you're not satisfied, we offer a full money-back guarantee within 14 days.",
  },
  {
    q: "Can multiple team members use one account?",
    a: "The Agency plan supports up to 5 team members. Enterprise plans offer unlimited seats. Solo plans (Starter, Pro) are for individual use.",
  },
  {
    q: "Is my data secure?",
    a: "Yes. All data is encrypted at rest and in transit. We never train our AI models on your proprietary brand data. Your content stays private.",
  },
  {
    q: "Do you offer a white-label solution?",
    a: "Yes, the Agency plan includes white-label exports. Enterprise customers can also get a fully white-labeled version of BrandForge for their clients.",
  },
];

function FAQItem({ faq, index }: { faq: { q: string; a: string }; index: number }) {
  const [open, setOpen] = useState(false);

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true }}
      transition={{ duration: 0.4, delay: index * 0.05 }}
      className="border border-white/10 rounded-2xl overflow-hidden"
      style={{ background: "rgba(255,255,255,0.02)" }}
    >
      <button
        className="w-full flex items-center justify-between px-6 py-5 text-left group"
        onClick={() => setOpen(!open)}
      >
        <span className="font-medium text-white group-hover:text-violet-300 transition-colors">
          {faq.q}
        </span>
        <ChevronDown
          className={`w-5 h-5 text-gray-400 flex-shrink-0 ml-4 transition-transform duration-300 ${
            open ? "rotate-180 text-violet-400" : ""
          }`}
        />
      </button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.div
            key="content"
            initial={{ height: 0, opacity: 0 }}
            animate={{ height: "auto", opacity: 1 }}
            exit={{ height: 0, opacity: 0 }}
            transition={{ duration: 0.3 }}
          >
            <div className="px-6 pb-5 text-gray-400 text-sm leading-relaxed border-t border-white/5">
              <div className="pt-4">{faq.a}</div>
            </div>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

export default function FAQ() {
  return (
    <section id="faq" className="py-28 relative overflow-hidden">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.7 }}
          className="text-center mb-14"
        >
          <span
            className="inline-block px-4 py-1.5 rounded-full text-sm font-medium mb-4 border"
            style={{
              background: "rgba(124,58,237,0.1)",
              borderColor: "rgba(124,58,237,0.3)",
              color: "#a78bfa",
            }}
          >
            Got Questions?
          </span>
          <h2 className="text-4xl sm:text-5xl font-extrabold text-white mb-4">
            Frequently Asked <span className="gradient-text">Questions</span>
          </h2>
          <p className="text-xl text-gray-400">
            Everything you need to know about BrandForge AI.
          </p>
        </motion.div>

        <div className="space-y-3">
          {faqs.map((faq, i) => (
            <FAQItem key={faq.q} faq={faq} index={i} />
          ))}
        </div>
      </div>
    </section>
  );
}
